// src/components/app-footer.vue
<script setup lang="ts">
import nodeModulesIcon from "~/assets/node-modules.svg?component";
import npmxIcon from "~/assets/npmx.svg?component";

const commitHash = __GIT_COMMIT_HASH__;
const commitUrl = `https://github.com/t128n/packy/commit/${commitHash}`;

const primaryStack = [
	{
		name: "WebContainers",
		url: "https://webcontainers.io",
		icon: "i-simple-icons:stackblitz",
	},
	{ name: "NPM", url: "https://www.npmjs.com/", icon: "i-simple-icons:npm" },
	{
		name: "Vue.js",
		url: "https://vuejs.org/",
		icon: "i-simple-icons:vuedotjs",
	},
	{ name: "Vite", url: "https://vitejs.dev/", icon: "i-simple-icons:vite" },
	{
		name: "Nuxt UI",
		url: "https://ui.nuxt.com/",
		icon: "i-simple-icons:nuxtdotjs",
	},
];

const additionalTools = [
	{ name: "npmx", url: "https://npmx.dev/", icon: npmxIcon },
	{
		name: "node-modules",
		url: "https://node-modules.dev/",
		icon: nodeModulesIcon,
	},
	{
		name: "pkg-size",
		url: "https://pkg-size.dev/",
		icon: "i-lucide:package-search",
	},
];
</script>

<template>
	<USeparator type="dashed" class="h-px" />

	<UFooter>
		<template #left>
			<div
				class="text-muted flex flex-wrap items-center gap-x-1 gap-y-1 text-sm"
			>
				<span>&copy; 2026 Torben Haack</span>
				<span>&sdot;</span>
				<a
					:href="commitUrl"
					target="_blank"
					rel="noreferrer"
					class="font-mono text-xs hover:underline"
					:title="commitHash"
					>{{ commitHash.slice(0, 7) }}
				</a>
			</div>
		</template>

		<template #right>
			<div class="flex flex-wrap items-center gap-1">
				<UButton
					icon="i-simple-icons:github"
					color="neutral"
					variant="ghost"
					to="https://github.com/t128n/packy"
					target="_blank"
					rel="noreferrer"
					aria-label="GitHub Repository"
					title="GitHub Repository"
				/>
				<UButton
					icon="i-lucide-globe"
					color="neutral"
					variant="ghost"
					to="https://t128.dev"
					target="_blank"
					rel="noreferrer"
					aria-label="Personal website"
					title="Personal website"
				/>
			</div>
		</template>

		<template #default>
			<div class="flex flex-col gap-1">
				<div
					class="text-muted flex flex-row flex-wrap items-center justify-center gap-1.5 text-xs"
				>
					<span>Powered by</span>
					<div
						v-for="(tech, index) in primaryStack"
						:key="tech.name"
						class="flex items-center"
					>
						<a
							:href="tech.url"
							target="_blank"
							rel="noreferrer"
							class="flex items-center hover:opacity-80"
							:aria-label="tech.name"
						>
							<UIcon :name="tech.icon" class="size-3" />
						</a>
						<span
							v-if="index < primaryStack.length - 1"
							class="ml-1.5"
							>,</span
						>
						<span v-else class="ml-1.5">.</span>
					</div>
				</div>

				<div
					class="text-muted flex flex-row flex-wrap items-center justify-center gap-1.5 text-xs"
				>
					<span>Enhanced by</span>
					<div
						v-for="(tool, index) in additionalTools"
						:key="tool.name"
						class="flex items-center"
					>
						<a
							:href="tool.url"
							target="_blank"
							rel="noreferrer"
							class="flex items-center hover:opacity-80"
							:aria-label="tool.name"
						>
							<UIcon :name="tool.icon" class="size-3" />
						</a>
						<span
							v-if="index < additionalTools.length - 1"
							class="ml-1.5"
							>,</span
						>
						<span v-else class="ml-1.5">.</span>
					</div>
				</div>

				<div class="text-muted flex justify-center text-xs">
					<span>Domain provided by</span>
					<a
						href="https://js.org/"
						target="_blank"
						rel="noreferrer"
						class="ml-1 inline-flex items-center gap-1 hover:underline"
					>
						<UIcon name="i-simple-icons:javascript" class="size-3" />
						.org
					</a>
				</div>
			</div>
		</template>
	</UFooter>
</template>

// src/components/app-footer.tsx
import { SiGithub, SiX } from "@icons-pack/react-simple-icons";

export function AppFooter() {
	// Read the injected commit SHA; fall back to undefined in dev
	const sha = typeof __COMMIT_SHA__ !== "undefined" ? (__COMMIT_SHA__ as string) : undefined;
	const shortSha = sha && sha !== "dev" ? sha.slice(0, 7) : undefined;
	const commitUrl = shortSha ? `https://github.com/t128n/packy/commit/${sha}` : "https://github.com/t128n/packy";

	return (
		<footer className="border-t border-border bg-background">
			<div className="mx-auto flex w-full max-w-7xl flex-col gap-3 px-4 py-3 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between">
				<div className="flex items-center gap-2">
					<span>© {new Date().getFullYear()} Torben Haack</span>
					<span className="text-muted-foreground/70">[t128n]</span>
					<a
						href="https://t128.github.io"
						target="_blank"
						rel="noreferrer"
						className="hover:text-foreground"
						aria-label="t128.github.io"
					>
						t128.github.io
					</a>
					{shortSha && (
						<a
							href={commitUrl}
							target="_blank"
							rel="noreferrer"
							className="inline-flex items-center gap-1.5 hover:text-foreground"
							aria-label={`Deployed commit ${shortSha}`}
						>
							<span className="text-muted-foreground/70">•</span>
							<span className="font-mono">{shortSha}</span>
						</a>
					)}
				</div>

				<div className="flex items-center gap-4">
					<div className="flex items-center gap-2">
						<a
							href="https://github.com/t128n/packy"
							target="_blank"
							rel="noreferrer"
							className="inline-flex items-center gap-1.5 hover:text-foreground"
							aria-label="GitHub repository"
						>
							<SiGithub className="h-3.5 w-3.5" aria-hidden="true" />
							<span className="sr-only">GitHub</span>
						</a>
						<a
							href="https://twitter.com/_t128n"
							target="_blank"
							rel="noreferrer"
							className="inline-flex items-center gap-1.5 hover:text-foreground"
							aria-label="Twitter profile"
						>
							<SiX className="h-3.5 w-3.5" aria-hidden="true" />
							<span className="sr-only">Twitter</span>
						</a>
					</div>
				</div>
			</div>
		</footer>
	);
}
